---
title: "✍️ Assessments"
subtitle: "Data for Data Science"
date: 27 October 2022
date-meta: 27 October 2022
---

# Submissions

Click on the assignments below to go to the Moodle page and submit your responses:

- **✍️ Formative Problem Set (01)  | W03-W05**: [Moodle link](https://moodle.lse.ac.uk/mod/coursework/view.php?id=1127006) & associated <a href="https://raw.githubusercontent.com/LSE-DSI/lse-ds202-course-notes/main/RMarkdown/DS202 2022 MT - Formative Assignment W03-W04.Rmd" download="DS202 2022 MT - Formative Assignment W03-W04.Rmd" target="_blank">RMarkdown file</a>. 
    - You can find model solutions [here](/assessments/formative1_solutions.qmd)
- **✍️ Summative Problem Set (01) | W05-W07**: [Moodle link](https://moodle.lse.ac.uk/mod/coursework/view.php?id=1131232&forceview=1) & associated [webpage](/assessments/summative1.qmd). 
    - Model solutions will be published 🔜 early W09 
- **✍️ Summative Problem Set (02) | W08-W10**: [Moodle link](https://moodle.lse.ac.uk/mod/assign/view.php?id=1139459&forceview=1) & associated [webpage](/assessments/summative2.qmd).
    - Use Slack to report any bugs or to ask for clarification.

# List of assessments

This course is assessed by a mix of problem sets and final exam. You can find the details below:

## 📝 Problem Sets (60%)

-   Summative problem sets released on **Weeks 5, 8 & 11**.
-   These will have a similar style to the formative problem sets, a mix of `R` tasks and your written interpretation of the analyses.
-   Typically, you will have 4-6 days to submit your solutions.
-   Each of the three summative problem sets is worth 20% of the final mark, and will be graded on a 100 point scale.

## ✍️ Exam (40%)

-   An open-book online exam.
-   3 hours for working on the exam + 1 hour for submission.
-   Exam questions will be comparable in style to the problem sets, but will require less writing of R code.
-   The exam questions will be released on Moodle sometime in the [Exam Period](https://info.lse.ac.uk/current-students/services/assessment-and-results/exams/exam-timetable). Our exact timeslot has not yet been confirmed by LSE Exams team.


