---
title: "LSE DS202"
subtitle: "Data Science for Social Scientists"
date: 13 November 2022
date-meta: 13 November 2022
---

# 📓 Syllabus

A list of what happens every week.

Click on each Week's link for more information (slides, lab instructions, recommended resources, etc.).

<table class="syllabus">
    <thead>
        
    </thead>
    
    <tr class="odd">
        <th colspan=4>Intro</th>
    </tr>

    <!-- WEEK 01 -->
    <tbody>
        <tr class="even">
            <td rowspan=2></td>
            <td rowspan=2>🗓️ <a href="/weeks/week01.qmd">W01</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Introduction, Context & Key Concepts <br/> [@james_introduction_2021, chapter 2]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td>No class this week. <br/>_(Use this time to revisit basic R programming)_</td>
        </tr>
    </tbody>

    <tr class="odd">
        <th colspan=4>Supervised Learning</th>
    </tr>

    <!-- WEEK 02 -->
    <tbody>
        <tr class="even">
           <td rowspan=2></td>
           <td rowspan=2>🗓️ <a href="/weeks/week02.qmd">W02</a></td>
           <td style="font-weight:bold;">Lecture</td>
           <td>Simple and Multiple Linear Regression <br/> [@james_introduction_2021, chapter 3]</td>
       </tr>
       <tr class="even">
           <td style="font-weight:bold;">Lab</td>
           <td>Revision of `R`: data structures, basic commands and some tidyverse</td>
       </tr>
   </tbody>

    <!-- WEEK 03 -->
    <tbody>
    <tr class="even">
        <td rowspan=3></td>
        <td rowspan=3>🗓️ <a href="/weeks/week03.qmd">W03</a></td>
        <td style="font-weight:bold;">Lecture</td>
        <td>Classifiers (Logistic Regression & Naive Bayes) <br/> [@james_introduction_2021, chapter 4]</td>
    </tr>
    <tr class="even">
        <td style="font-weight:bold;">Lab</td>
        <td>Linear Regression [@james_introduction_2021, chapter 3]</td>
    </tr>
    <tr class="even">
        <td style="font-weight:bold;">Formative</td>
        <td>
            <ul>
                <li>Worth: knowledge!</li>
                <li>Problem set involving linear regression.</li>
                <li>**Release date:** 15 October 2022</li> ([link to Moodle](https://moodle.lse.ac.uk/mod/coursework/view.php?id=1127006))
                <li>**Deadline:** 25 October 2022 (Week 05)</li>
            </ul>
        </td>
    </tr>
   </tbody>

    <!-- WEEK 04 -->
    <tbody>
        <tr class="even">
            <td rowspan=2></td>
            <td rowspan=2>🗓️ <a href="/weeks/week04.qmd">W04</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Resampling methods <br/> [@james_introduction_2021, chapter 5]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td>Classification Methods [@james_introduction_2021, chapter 4]</td>
        </tr>
       </tbody>

    <!-- WEEK 05 -->
    <tbody>
        <tr class="even">
            <td rowspan=3></td>
            <td rowspan=3>🗓️ <a href="/weeks/week05.qmd">W05</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Non-linear algorithms (SVM & tree-based models) <br/> [@james_introduction_2021, chapter 8-9]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td>Cross-Validation and the Bootstrap [@james_introduction_2021, chapter 5]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Summative</td>
            <td>
                <ul>
                    <li>Worth: 20% of final marks</li>
                    <li>Problem set involving regression, classification and resampling</li>
                    <li>**Release date:** 28 October 2022</li>
                    <li>**Deadline:** 9 November 2022 (Week 07)</li>
                </ul>
            </td>
        </tr>
    </tbody>

    <tr class="odd">
        <th colspan=4>Unsupervised Learning</th>
    </tr>

    <!-- WEEK 07 -->
    <tbody>
        <tr class="even">
            <td rowspan=2></td>
            <td rowspan=2>🗓️ <a href="/weeks/week07.qmd">W07</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Unsupervised Learning: Clustering <br/> [@james_introduction_2021, chapter 12]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td>Tree-based models [@james_introduction_2021, chapter 8]</td>
        </tr>
    </tbody>

    <!-- WEEK 08 -->
    <tbody>
        <tr class="even">
            <td rowspan=3></td>
            <td rowspan=3>🗓️ <a href="/weeks/week08.qmd">W08</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Unsupervised Learning: Dimensionality Reduction <br/> [@james_introduction_2021, chapter 12]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td>Support Vector Machine + `tidymodels` + recap of cross-validation [@james_introduction_2021, chapter 5, 9]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Summative</td>
            <td>
                <ul>
                    <li>Worth: 20% of final marks</li>
                    <li>Problem set about unsupervised learning</li>
                    <li>**Release date:** 18 November 2022</li>
                    <li>**Deadline:** 29 November 2022 (Week 10)</li>
                </ul>
            </td>
        </tr>
    </tbody>

    <tr class="odd">
        <th colspan=4>Applications</th>
    </tr>

    <!-- WEEK 09 -->
    <tbody>
        <tr class="even">
            <td rowspan=3></td>
            <td rowspan=3>🗓️ <a href="">W09</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Applications: Text as Data & Topic Modelling </td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold">Guest:</td>
            <td>Prof. [Ken Benoit](https://kenbenoit.net/)</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td> Unsupervised Learning: Clustering [@james_introduction_2021, chapter 12]</td>
        </tr>
    </tbody>

    <!-- WEEK 10 -->
    <tbody>
        <tr class="even">
            <td rowspan=3></td>
            <td rowspan=3>🗓️ <a href="">W10</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Applications: Predictive Modelling on Tabular Data</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td>Unsupervised Learning: Principal Component Analysis [@james_introduction_2021, chapter 12]</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Summative</td>
            <td>
                <ul>
                    <li>Worth: 20% of final marks</li>
                    <li>Problem set about ML applications (text mining/social media)</li>
                    <li>**Release date:** 2 December 2022</li>
                    <li>**Deadline:** 15 December 2022 (Week 11+1)</li>
                </ul>
            </td>
        </tr>
    </tbody>

    <!-- WEEK 11 -->
    <tbody>
        <tr class="even">
            <td rowspan=3></td>
            <td rowspan=3>🗓️ <a href="">W11</a></td>
            <td style="font-weight:bold;">Lecture</td>
            <td>Applications: Social Media Data</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold">Guest:</td>
            <td>[Sara Luxmoore](https://www.linkedin.com/in/sara-luxmoore/), MSc in Applied Social Data Science (LSE)</td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">Lab</td>
            <td>We will explore unsupervised models using a couple of text datasets</td>
        </tr>
    </tbody>

    <tbody>
        <tr class="even">
            <td rowspan=2></td>
            <td rowspan=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td style="font-weight:bold;"></td>
            <td></td>
        </tr>
        <tr class="even">
            <td style="font-weight:bold;">...</td>
            <td></td>
        </tr>
    </tbody>

    <tbody>
        <tr class="even">
            <td rowspan=2></td>
            <td rowspan=2>🗓️ <a href="">Jan/23</a></td>
            <td style="font-weight:bold;">Exam</td>
            <td>
                <ul>
                    <li>Worth: 40% of final marks</li>
                    <li>Problem set about supervised + unsupervised learning + applications</li>
                    <li>3 hours + 1 hour for submission</li>
                    <li>Online exam via Moodle</li>
                    <li>**Date:** Sometime during the [Exam Period](https://info.lse.ac.uk/current-students/services/assessment-and-results/exams/exam-timetable). Exact timeslot has not yet been confirmed by LSE Exams team.</li>
                </ul>
            </td>
        </tr>
    <tbody>
    
</table>