---
title: "👨‍🏫 Week 10 - Lecture"
date: 2 December 2022
date-meta: 2 December 2022
---

::: {.callout-tip collapse="true"}

## Info about this lecture

The original title of this week's lecture was _Applications: Predictive Modelling on Tabular Data_ but since we have been talking a lot about tabular data (in the context of supervised learning), we are going to bring diverse applications from our areas of expertise instead:

- In the first hour of the lecture, I will deliver a gentle introduction to the principles of network analysis, and I will demonstrate it using a software called [Gephi](https://gephi.org/).
    - Those of you pursuing degrees in Economics might be interested in the application of this type of techniques to the [networked dynamics of trade](https://oec.world/en/visualize/network/hs92/export/chl/all/show/2020/).
- In the second hour, Dr. [Stuart Bramwell](https://www.lse.ac.uk/Methodology/People/Academic-Staff/Stuart-Bramwell/Stuart-Bramwell) will talk about his work on the [WhoGov dataset](https://politicscentre.nuffield.ox.ac.uk/whogov-dataset/), and what this data tell us about cabinets around the world (autocracies vs democracies, the role of gender).
:::


## Part I - Network Analysis (Live Demo)

<details><summary>**Click here for the links mentioned in the lecture**</summary>

### Software & Data

- Download [Gephi](https://gephi.org/)
- Check out this tutorial of [Network Analysis with R](https://kateto.net/netscix2016.html) by Katherine Ognyanova.
- Tons of network data at [SNAP Stanford Repository](http://snap.stanford.edu/data/)

### Blogs and online tutorials

- [A Gephi of Ice and Fire: Visualizing George R.R. Martin's Game of Thrones Series](https://studentwork.prattsi.org/infovis/labs/a-gephi-of-ice-and-fire-visualizing-george-r-r-martins-game-of-thrones-series/)
- [More Game of Thrones networks](https://medium.com/@sanchit_kumar/my-experience-with-gephi-visualizing-game-of-thrones-a-song-of-ice-and-fire-61587eefba9d)

### Academic Articles

- Silva, J., Bennett, L., Papageorgiou, L. et al. **A mathematical programming approach for sequential clustering of dynamic networks.** Eur. Phys. J. B 89, 39 (2016). [https://doi.org/10.1140/epjb/e2015-60656-5](https://doi.org/10.1140/epjb/e2015-60656-5)

- Cardoso-Silva, J., Papageorgiou, L.G. & Tsoka, S. **Network-based piecewise linear regression for QSAR modelling**. J Comput Aided Mol Des 33, 831–844 (2019). [https://doi.org/10.1007/s10822-019-00228-6])https://doi.org/10.1007/s10822-019-00228-6)

- Caterina De Bacco et al. **Latent Network Models to Account for Noisy, Multiply-Reported Social Network Data.** Accepted at Journal of the Royal Statistical Society - Statistics in Society - Series A. Preprint available online: [arXiv:2112.11396v1](https://arxiv.org/pdf/2112.11396.pdf)


</details>


## Part II - Understanding cabinets globally through WhoGov

A talk by Dr. [Stuart Bramwell](https://www.lse.ac.uk/Methodology/People/Academic-Staff/Stuart-Bramwell/Stuart-Bramwell).

Check Moodle to download the slides.