---
title: "👨‍🏫 Week 04 - Lecture"
date: 21 October 2022
date-meta: 21 October 2022
---

# Topic: Resampling methods

There are no slides this week! Instead, you will form groups (of five people) and we will run a couple of live experiments together. 

- 💻 Bring your laptop or team up with someone who will bring one!

## How this is going to work

1. Head over to [📥W04 Lecture Files](https://moodle.lse.ac.uk/mod/folder/view.php?id=1129071) (on Moodle) to download the files you will need for this lecture.

2. You will form groups of five people to work on getting the "best" model for your specific dataset by following a set of tasks marked as **🎯 ACTION POINT** in the RMarkdown.

3. As you work on the solutions, you will send me the responses on Slack and I will update the tables below live during the lecture. The final outcome will be available on the website later.


::: {.callout-tip collapse="true"}
## If there are no slides, how do I revise this later?

- You can read all about resampling methods in our textbook, more specifically [@james_introduction_2021, Chapter 5].
- The RMarkdown you will use during the lecture will help you revise later, too.


:::

<details>
<summary>**The Setup**: Click here to understand how I created the datasets used in this lecture</summary>

### The cross-validation setup

How did I create the datasets you are using in this lecture?

#### Step 1:

First, I selected the dataset `Wage` from the ISLR2 package in R and randomly split it into two subsets:

- $10\%$ for <mark>external validation set</mark>: this is a portion of data that I have kept hidden from everyone.  
- $90\%$ available for model training, that I further distributed to groups. I call this the <mark>internal validation set</mark>

#### Step 2: 

I then took the internal validation set and further split it into five random subsets:

::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;background-color:#fdd0c6;color:#fdd0c6;color:#fdd0c6"}
Fold1
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;background-color:#fdd0c6;color:#fdd0c6"}
Fold2
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;background-color:#fdd0c6;color:#fdd0c6"}
Fold3
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;background-color:#fdd0c6;color:#fdd0c6"}
Fold4
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;background-color:#fdd0c6;color:#fdd0c6"}
Fold5
:::

We call each of this subsets a <mark>fold</mark>. Therefore, we have 5 folds of data.

#### Step 3:

The point of doing this is to perform <mark>cross-validation</mark>. The goal is to answer the following question: 

> _How well does our model perform on data it has not seen yet?_

Notice that this goes beyond asessing goodness-of-fit. Instead of focusing on how well our model _fits the current data_, we ask whether it would still be generalisable should be receive new data. 

How do we do that? We could run the same model on different subsets of the data, holding one of the folds for testing.

For example:

::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;color:#ffffff;border-color:#fefefe; margin:1%;text-align:center;background-color:#fb6341"}
Test
:::

#### Step 4:

Since I have split the data into five folds, I could train and test algorithms using five different splits of my data. This 5-fold cross-validation looks like this:


::: {style="display:inline-block;width: 90px;height=60px;border-style: none;color:#212121;margin:1%;"}
**Split 1:**
:::

::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;color:#ffffff;border-color:#fefefe; margin:1%;text-align:center;background-color:#fb6341"}
Test
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
::: 

<br/>

::: {style="display:inline-block;width: 90px;height=60px;border-style: none;color:#212121;margin:1%;"}
**Split 2:**
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;color:#ffffff;border-color:#fefefe; margin:1%;text-align:center;background-color:#fb6341"}
Test
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::

<br/>

::: {style="display:inline-block;width: 90px;height=60px;border-style: none;color:#212121;margin:1%;"}
**Split 3:**
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;color:#ffffff;border-color:#fefefe; margin:1%;text-align:center;background-color:#fb6341"}
Test
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::

<br/>

::: {style="display:inline-block;width: 90px;height=60px;border-style: none;color:#212121;margin:1%;"}
**Split 4:**
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;color:#ffffff;border-color:#fefefe; margin:1%;text-align:center;background-color:#fb6341"}
Test
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::

<br/>

::: {style="display:inline-block;width: 90px;height=60px;border-style: none;color:#212121;margin:1%;"}
**Split 5:**
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;color:#fdd0c6;border-width: 1px;border-color:#fefefe;margin:1%;background-color:#fdd0c6"}
Train
:::
::: {style="display:inline-block;width: 60px;height=60px;border-style: dotted;border-width: 1px;color:#ffffff;border-color:#fefefe; margin:1%;text-align:center;background-color:#fb6341"}
Test
:::

Each group will be working on a separate split of this data. You will train your models on 80% of the data, evaluate the goodness-of-fit in the training data, then assess the performance in the test data. Once you find a model that has a good performance, balanced in training vs test data, then we will see how well your model performs in the **external data set**.

</details>


The action points below will be updated during the lecture:

<details>

<summary>**🎯 ACTION POINT 1**: Check if your numbers match</summary>

<br/>


::: {style="display:inline-block;width: 30.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}

##### 🗄️ DATASET 1

Distribution of `above150k`

(Training)
```r
  No  Yes 
1910  250 
```

(Test)
```r
 No Yes 
473  67 
```

:::

::: {style="display:inline-block;width: 30.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}

##### 🗄️ DATASET 2

Distribution of `above150k`

(Training)
```r
  No  Yes 
1900  260 
```

(Test)
```r
 No Yes 
483  57 
```

:::

::: {style="display:inline-block;width: 30.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}

##### 🗄️ DATASET 3

Distribution of `above150k`

(Training)
```r
  No  Yes 
1904  256 
```

(Test)
```r
 No Yes 
479  61 
```

:::

::: {style="display:inline-block;width: 30.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}

##### 🗄️ DATASET 4

Distribution of `above150k`

(Training)
```r
  No  Yes 
1915  245 
```

(Test)
```r
 No Yes 
468  72  
```

:::

::: {style="display:inline-block;width: 30.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}

##### 🗄️ DATASET 5

Distribution of `above150k`

(Training)
```r
  No  Yes 
1903  257 
```

(Test)
```r
 No Yes 
480  60 
```

:::


::: {style="display:inline-block;width: 30.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fff4ea"}

##### 🗄️ EXTERNAL DATA

Distribution of `above150k`

Just for your knowledge:

```r
 No Yes 
274  26 
```

:::

</details>



<details>

<mark class="todo"></mark>

<summary>**🎯 ACTION POINT 2 & 3**: Tell us your best threshold (training data)</summary>

**DATASET 1**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Sofie**

- Best threshold = $$ 

(Training Stats)

- Accuracy = $$
- TNR = $$
- TPR = $$
- Precision = $$
- Recall = $$
- F1-score = $$
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Yujia**

- Best threshold = $0.245$ 

(Training Stats)

- Accuracy = $82.41 \%$
- TNR = $ 84.97 \%$
- TPR = $ 62.80 \%$
- Precision = $ 35.36 \%$
- F1-score = $0.4524496$
:::


**DATASET 2**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Vansh**

- Best threshold = $0.2$ 

(Training Stats)

- Accuracy = $79.44 \%$
- TNR = $80.58 \%$
- TPR = $71.15 \%$
- Precision = $33.39 \%$
- F1-score = $0.4545$
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Ekki**

- Best threshold = $$ 

(Training Stats)

- Accuracy = $$
- TNR = $$
- TPR = $$
- Precision = $$
- Recall = $$
- F1-score = $$
:::



**DATASET 3**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Yoyo**

- Best threshold = $0.23$ 

(Training Stats)

- Accuracy = $81.85 \%$
- TNR = $84.40 \%$
- TPR = $62.89 \%$
- Precision = $35.15 \%$
- F1-score = $0.4509804$
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Diljot**

- Best threshold = $$ 

(Training Stats)

- Accuracy = $$
- TNR = $$
- TPR = $$
- Precision = $$
- Recall = $$
- F1-score = $$
:::



**DATASET 4**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Ashley**

- Best threshold = $0.23$ 

(Training Stats)

- Accuracy = $ 83.94 \%$
- TNR = $ 86.95 \%$
- TPR = $60.41 \%$
- Precision = $ 37.19 \%$
- F1-score = $0.4603421$
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Lisa**

- Best threshold = $$ 

(Training Stats)

- Accuracy = $$
- TNR = $$
- TPR = $$
- Precision = $$
- Recall = $$
- F1-score = $$
:::



**DATASET 5**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Paul Keenan**

- Best threshold = $0.245$ 

(Training Stats)

- Accuracy = $82.59259 \%$
- TNR = $85.54913 \%$
- TPR (Recall) = $60.70039 \%$
- Precision = $36.1949 \%$
- F1-score = $0.4534884$
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **Andres**

- Best threshold = $0.25$ 

(Training Stats)

- Accuracy = $83.01 \%$
- TNR = $86.50 \%$
- TPR (Recall) = $57.20 \%$
- Precision = $36.39 \%$
- F1-score = $0.4447806 $
:::

</details>

</details>

<details>
<summary>**🎯 ACTION POINT 4 & 5**: What is the best threshold both for training and test?</summary>

<mark class="todo"></mark>

<details><summary>**DATASET 1**</summary>

**DATASET 1**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $$ 

(Training vs Test)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

</details>

<details><summary>**DATASET 2**</summary>

**DATASET 2**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

</details>

<details><summary>**DATASET 3**</summary>

**DATASET 3**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

</details>

<details><summary>**DATASET 4**</summary>

**DATASET 4**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

</details>

<details><summary>**DATASET 5**</summary>

**DATASET 5**

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

::: {style="display:inline-block;width: 40.5%;border-style: dotted;border-width: 1px;border-color: &quot;#fefefe&quot;; margin:1%;padding:1.5%;background-color:#fafafa"}
🗣️ **\<Person\>**

- Best threshold = $ $ vs $ $ 

(Training Stats)

- Accuracy = $ $ vs $ $
- TNR = $ $ vs $ $
- TPR = $ $ vs $ $
- Precision = $ $ vs $ $
- Recall = $ $ vs $ $
- F1-score = $ $ vs $ $
:::

</details>
</details>

<details>

<summary>**🎯 ACTION POINT 6 & 7**: What about the external dataset?</summary>
<br/>

<mark class="todo"></mark>

You will be asked to upload your model to Slack. I will then run your model on the external data and report back the results!

</details>
