on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Install rmarkdown
        run: install.packages("rmarkdown")
        shell: Rscript {0}
      
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Install tidyverse
        run: install.packages("tidyverse")
        shell: Rscript {0}
      
      - name: Install ggpubr
        run: install.packages("devtools");devtools::install_version("MatrixModels", version="0.5.0");install.packages("ggpubr")
        shell: Rscript {0}

      - name: Install ISLRv2
        run: install.packages("ISLR2")
        shell: Rscript {0}

      - name: Install packages used throughout Quarto markdown files
        run: install.packages(c("pROC", "ISLR2", "e1071", "ggcorrplot", "car", "cvms", "rsample", "ggsci", "palmerpenguins", "GGally"))
        shell: Rscript {0}

      - name: Install tidymodels
        run: install.packages(c("tidymodels"))
        shell: Rscript {0}

      - name: Install rpart packages
        run: devtools::install_version("rpart", version = "4.1.16", repos = "http://cran.us.r-project.org");install.packages(c("rpart.plot"))
        shell: Rscript {0}

      - name: Install 
        run: install.packages("remotes"); remotes::install_github("grantmcdermott/parttree", force=TRUE)
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
